spring:
  application:
    name: proyectoarqui
  datasource:
    url: jdbc:mysql://34.196.3.194:3308/patikas
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
      hibernate:
        ddl-auto: update
    show-sql: false

server:
    port: 8080


